// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrbhlsitkbobhpmnyqld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyYmhsc2l0a2JvYmhwbW55cWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0ODMyMjUsImV4cCI6MjA3OTA1OTIyNX0.0wjW7zVYkdURJn8BFem4ZkpoFELXC9ZxlTM48W1M-EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Admin client for server-side operations
let adminSupabase: ReturnType<typeof createClient<Database>> | null = null;

export const getAdminSupabase = () => {
  if (!adminSupabase) {
    // In a real application, this would come from an environment variable
    // For now, we'll use the publishable key since this is a simplified setup
    adminSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
  return adminSupabase;
};